# Generated by Django 5.1.3 on 2024-12-07 16:28

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roombook_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('«Двухместный номер с 1 кроватью»', '«Двухместный номер с 1 кроватью»'), ('«Одноместный номер эконом-класса»', '«Одноместный номер эконом-класса»'), ('«Улучшенный люкс с кроватью размера «king-size»', '«Улучшенный люкс с кроватью размера «king-size»'), ('«Семейный номер»', '«Семейный номер»')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('свободен', 'свободен'), ('забронирован', 'забронирован'), ('занят', 'занят')], max_length=100),
        ),
    ]
