# Generated by Django 5.1.3 on 2024-12-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
