# Generated by Django 5.1.3 on 2024-12-07 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombook',
            name='number',
        ),
        migrations.AddField(
            model_name='roombook',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombook',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_books', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombook',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombook',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
