# Generated by Django 5.1.3 on 2024-12-07 18:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_booking_room_remove_booking_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('«Двухместный номер с 1 кроватью»', '«Двухместный номер с 1 кроватью»'), ('«Одноместный номер эконом-класса»', '«Одноместный номер эконом-класса»'), ('«Улучшенный люкс с кроватью размера «king-size»', '«Улучшенный люкс с кроватью размера «king-size»'), ('«Семейный номер»', '«Семейный номер»')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
